-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 23:14:44 2025 and edited
-- Large edit was in NetProfit as I wanted it to be Revenue - Budget compared to mwb file
-- Model: Campaign_Channel    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Campaign_Channel
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Campaign_Channel` DEFAULT CHARACTER SET utf8 ;
USE `Campaign_Channel` ;

-- -----------------------------------------------------
-- Table `Campaign_Channel`.`Channel_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Campaign_Channel`.`Channel_Category` ;

CREATE TABLE IF NOT EXISTS `Campaign_Channel`.`Channel_Category` (
  `idChannel_Category` INT NOT NULL AUTO_INCREMENT,
  `Channel_CategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idChannel_Category`),
  UNIQUE INDEX `Channel_CategoryName_UNIQUE` (`Channel_CategoryName` ASC),
  UNIQUE INDEX `idChannel_Category_UNIQUE` (`idChannel_Category` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Campaign_Channel`.`Channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Campaign_Channel`.`Channel` ;

CREATE TABLE IF NOT EXISTS `Campaign_Channel`.`Channel` (
  `idChannel` INT NOT NULL AUTO_INCREMENT,
  `ChannelName` VARCHAR(45) NOT NULL,
  `idChannel_Category` INT NOT NULL,
  PRIMARY KEY (`idChannel`),
  UNIQUE INDEX `idChannel_UNIQUE` (`idChannel` ASC),
  UNIQUE INDEX `ChannelName_UNIQUE` (`ChannelName` ASC),
  INDEX `fk_Channel_Channel_Category1_idx` (`idChannel_Category` ASC),
  CONSTRAINT `fk_Channel_Channel_Category1`
    FOREIGN KEY (`idChannel_Category`)
    REFERENCES `Campaign_Channel`.`Channel_Category` (`idChannel_Category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Campaign_Channel`.`Campaign_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Campaign_Channel`.`Campaign_Category` ;

CREATE TABLE IF NOT EXISTS `Campaign_Channel`.`Campaign_Category` (
  `idCampaign_Category` INT NOT NULL AUTO_INCREMENT,
  `Campaign_CategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCampaign_Category`),
  UNIQUE INDEX `idCategory_UNIQUE` (`idCampaign_Category` ASC),
  UNIQUE INDEX `CategoryName_UNIQUE` (`Campaign_CategoryName` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Campaign_Channel`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Campaign_Channel`.`Company` ;

CREATE TABLE IF NOT EXISTS `Campaign_Channel`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompany`),
  UNIQUE INDEX `idCompany_UNIQUE` (`idCompany` ASC),
  UNIQUE INDEX `CompanyName_UNIQUE` (`CompanyName` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Campaign_Channel`.`Campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Campaign_Channel`.`Campaign` ;

CREATE TABLE IF NOT EXISTS `Campaign_Channel`.`Campaign` (
  `idCampaign` INT NOT NULL AUTO_INCREMENT,
  `Campaign_Name` VARCHAR(100) NOT NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `idCompany` INT NOT NULL,
  `idCampaign_Category` INT NOT NULL,
  `Budget` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `Revenue` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `NetProfit` DECIMAL(15,2) AS (Revenue - Budget) STORED,
  PRIMARY KEY (`idCampaign`),
  UNIQUE INDEX `idCampaign_UNIQUE` (`idCampaign` ASC),
  UNIQUE INDEX `Campaign_Name_UNIQUE` (`Campaign_Name` ASC),
  INDEX `fk_Campaign_Company1_idx` (`idCompany` ASC),
  INDEX `fk_Campaign_Campaign_Category1_idx` (`idCampaign_Category` ASC),
  CONSTRAINT `fk_Campaign_Company1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `Campaign_Channel`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Campaign_Campaign_Category1`
    FOREIGN KEY (`idCampaign_Category`)
    REFERENCES `Campaign_Channel`.`Campaign_Category` (`idCampaign_Category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Campaign_Channel`.`Campaign_channel_xref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Campaign_Channel`.`Campaign_channel_xref` ;

CREATE TABLE IF NOT EXISTS `Campaign_Channel`.`Campaign_channel_xref` (
  `idChannel` INT NOT NULL,
  `idCampaign` INT NOT NULL,
  PRIMARY KEY (`idChannel`, `idCampaign`),
  INDEX `fk_Channel_has_Campaign_Campaign1_idx` (`idCampaign` ASC),
  INDEX `fk_Channel_has_Campaign_Channel1_idx` (`idChannel` ASC),
  CONSTRAINT `fk_Channel_has_Campaign_Channel1`
    FOREIGN KEY (`idChannel`)
    REFERENCES `Campaign_Channel`.`Channel` (`idChannel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Channel_has_Campaign_Campaign1`
    FOREIGN KEY (`idCampaign`)
    REFERENCES `Campaign_Channel`.`Campaign` (`idCampaign`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
